project:
  type: website
  output-dir: docs

website:
  title: "Joshua Gladwell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/projects.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
  search: false
  google-analytics: "G-6DPLBLTB6E"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

