project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: ./assets/logo/logo_white.svg
    logo-alt: "Joshua Gladwell"
    foreground: 'white'
    background: '#275F58'
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: projects/projects.qmd
        text: Projects
      - href: blog/blog.qmd
        text: Blog
  search: false
  favicon: ./assets/logo/logo_green_white.svg
  google-analytics: 
    tracking-id: "G-6DPLBLTB6E"


format:
  html:
    theme: cosmo
    mainfont: Optima
    css: styles.css
    toc: true
