project:
  type: website

website:
  title: "Joshua Gladwell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/about.qmd
        text: About
      - href: projects/projects.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

